title: Singapore-China International Commercial Dispute Resolution Conference 2022
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# favicon: /images/favicon-isomer.ico

# Site colors
colors:
  primary-color: '#18386B' #dark blue
  secondary-color: '#AC8B60' #caramel
  media-colors:
    - title: media-color-one
      color: '#18386B'
    - title: media-color-two
      color: '#AC8B60'
    - title: media-color-three
      color: '#939393'
    - title: media-color-four
      color: '#939393'
    - title: media-color-five
      color: '#939393'


collections:
  conference:
    output: true
  videos:
    output: true
  speakers-and-moderators:
    output: true
  key-partners:
    output: true
google_analytics:<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-VD8X2NLBLZ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-VD8X2NLBLZ');
</script>
resources_name: news

description: An Isomer site of the Singapore Government

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
